# SPDX-FileCopyrightText: 2023 Adafruit Industries
#
# SPDX-License-Identifier: MIT

# This is where you store the credentials necessary for your code.
# The associated demo only requires WiFi, but you can include any
# credentials here, such as Adafruit IO username and key, etc.

 


WIFI_SSID = ""
WIFI_PASSWORD = ""

WEATHER_KEY="ctpe2272nswh94og"
LOCATION = "SHENZHEN"